### ISSUE TITLE
ERROR: Service 'crane_registry' failed to build

### ISSUE THREAD

**Issue by tangjiquan** [Dataman-Cloud/crane#644] opened 2017-03-31 04:45 UTC
Step 1 : FROM registry:2.5.1
ERROR: Service 'crane_registry' failed to build: Get https://registry-1.docker.io/v2/library/registry/manifests/2.5.1: read tcp 10.1.217.66:51883->50.17.62.194:443: read: connection reset by peer

**Comment by xiaods** [comment] 2017-04-01 15:52
Hi @tangjiquan , this is caused by GFW block. maybe a china hosting image can resolve it. let me think about it.

**Comment by tangjiquan** [comment] 2017-04-06 01:35
thank you， I've got the source code。
This is caused by GFW block.

**Comment by xiaods** [comment] 2017-04-09 00:34
fixed by use proxy

**Closed by xiaods** 2017-04-09 00:34 UTC
Labels: enhancement
